id: linkerd-opentelemetry
displayName: Linkerd (OpenTelemetry Collector)
description: |
  Monitor Linkerd service mesh using OpenTelemetry Collector. Collect comprehensive metrics from proxy sidecars, control plane components, and Kubernetes workloads across self-hosted and managed Kubernetes clusters.
install:
  primary:
    link:
      url: https://docs.newrelic.com/docs/opentelemetry/integrations/linkerd/linkerd-otel-overview/
icon: logo.png

keywords:
  - linkerd
  - service mesh
  - kubernetes
  - opentelemetry
  - open telemetry
  - otel linkerd
  - mtls
  - proxy
  - infrastructure
  - open source monitoring

categoryTerms:
  - open source monitoring
  - infrastructure
