slug: ebpf-ai-monitoring
description: |
  ## eBPF AI monitoring highlights
  The New Relic eBPF AI monitoring lets you observe the AI-layer of your tech stack, giving you a holistic overview of the health and performance of your AI-powered app and includes pre-built dashboards visualizing:
  Requests
  Errors
  Token usage
  Response time

summary: |
  Effectively monitor services using New Relic's zero-instrumentation eBPF agent - AI monitoring mode.
icon: logo.svg
level: New Relic
authors:
  - New Relic
title: eBPF AI monitoring
documentation:
  - name: eBPF installation docs
    description: |
      Use New Relic eBPF agent to monitor your services.
    url: https://docs.newrelic.com/docs/kubernetes-pixie/kubernetes-integration/installation/eapm/
dataSourceIds:
  - ebpf
keywords:
  - language agent
  - eAPM
  - eBPF
  - eBPF AI monitoring
dashboards:
  - ebpf-ai-monitoring
