id: 9e721dc6-e854-4a7f-86ef-c256209fbc91
slug: salesforce-eventlog-for-logs
title: Salesforce Event Exporter
description: |
  ## What is Salesforce Event Exporter?

  The New Relic Salesforce Exporter is an open-source integration designed to provide a unified view of Salesforce telemetry by funneling logs and performance metrics into the New Relic platform. It consists of two primary components: an Event Log integration that batches data from the Query, Tooling, and Limits APIs, and an Event Stream integration that captures real-time security alerts via the Pub/Sub API. Users can monitor a wide range of activities, including Apex performance, user access, and platform resource limits, to ensure operational health and security.

  ### New Relic and Salesforce Exporter

  The New Relic Salesforce Exporter integration allows you to process and forward Salesforce Event Log files and Event Streams to New Relic. Our event monitoring product gathers information about your Salesforce org’s operational events, which you can use to analyze usage trends and user behavior.

  ### Why monitor Salesforce events with New Relic?

  The New Relic Salesforce Exporter monitoring quickstart helps you view the granular details of user activities in your organization. With the integration, you can track trends in events, identify suspicious user behavior, and protect your firm’s data. What’s more, you can identify parts of your organization that aren’t performing up to expectation, thereby gaining insights on which performance to optimize.
  To allow New Relic monitoring products to collect Salesforce events, you need to have read access to the Salesforce Event Logs, real-time events, and enable the Salesforce event log file API.
  Install the New Relic Salesforce Event Log quickstart today to instantly monitor your organization’s Salesforce events in real-time. The instant observability quickstart is the key to a seamless Salesforce Event Log monitoring.

  ## Dashboards

  Visualize the following aspects of any Salesforce org to get a clear picture of your environment:
  - Apex usage and performance
  - Lightning usage and performance
  - Errors, permissions and violations
  - Real-time security alerts
  - User access
  - API access
  - Documents, contents and DB access
  - Report access
  - CRM analytics (Wave) usage and performance
  - Org limits

summary: |
  Monitoring Salesforce Event Log and Event Streams is critical to ensure that you track events’ trends, and detect suspicious user behavior. Install the New Relic quicksart to proactively monitor Saleforce Event.
icon: logo.png
level: Community

keywords:
  - nrlabs
  - nrlabs-data
  - nrlabs-viz
  - salesforce
  - salesforce event log
  - salesforce event stream
  - salesforce exporter
  - NR1_addData
  - NR1_sys
authors:
  - New Relic Labs
documentation:
  - name: Salesforce Exporter integration for New Relic
    description: |
      Salesforce Exporter integration for New Relic Logs offers an integration to process and forward Salesforce events to New Relic Logs.
    url: github.com/newrelic/newrelic-salesforce-exporter/
  - name: Salesforce Dashboards
    description: |
      Salesforce dashboard provides visualization into the usage, performance and security details of your salesforce organization.
    url: https://github.com/newrelic/newrelic-salesforce-exporter/tree/main/dashboards/installer
dataSourceIds:
  - salesforce-eventlog-for-logs
dashboards:
  - salesforce-apex
  - salesforce-lightning
  - salesforce-errors
  - salesforce-security
  - salesforce-user
  - salesforce-api
  - salesforce-docs
  - salesforce-limits
  - salesforce-report
  - salesforce-wave