id: metricshub
displayName: MetricsHub
description: |
  MetricsHub is an OpenTelemetry-native metrics collector. Remotely monitor the hardware health of your servers, storage systems, and network switches, as well as the performance and status of your operating systems and databases.
icon: logo.svg
install:
  primary:
    link:
      url: https://metricshub.com/docs/latest/configuration/sending-telemetry-to-observability-platforms
keywords:
  - agent
  - hardware
  - infrastructure
  - storage
  - networking
  - opentelemetry
  - sustainability
  - metricshub
  - system
  - os
  - operating system
  - windows
  - linux
  - unix
  - database
categoryTerms:
  - infrastructure
  - network
