slug: anthropic
description: |
  ## Overview
  Developers are adopting generative AI for innovation, using client-side processing and semantic searches over domain-specific knowledge bases. Various tools use large language models (LLMs) like Anthropic to create AI agents, systems, or apps that perform complex queries and integrate with multiple third-party services. One of the success factors for businesses is efficient cost tracking and management.

  New Relic provides a real-time solution for tracking and revealing the full context of used technologies, service interaction topology, and observability metrics (traces, logs, and business events) for your Anthropic-powered applications.

  ## Use cases

  ### Monitor service health and performance
  - Detect bottlenecks by tracking real-time metrics, including request counts, durations, and error rates.
  - Manage service costs with automated cost calculations for each request.
  - Stay on track with SLOs.

  ### Monitor service quality and cost
  - Set up error budgets for performance and cost controls.
  - Validate consumption and response time by model.
  - Prevent quality degradation by validating models and usage patterns in real time.

  ### End-to-end tracing and debugging
  - Achieve complete visibility of prompt flows, from initial request to final response, for faster root cause analysis.
  - Capture detailed debug data to troubleshoot issues in complex pipelines.
  - Streamline workflows with granular tracing of LLM prompts, including response latency and model-level metrics.
  - Resolve issues quicker by pinpointing exact problem areas in prompts, tokens, or system integrations.

  ### Build trust, reduce compliance and audit risks
  - Track every input and output for an audit trail.
  - Query all data in real time and store for future reference.
  - Maintain full data lineage from initial prompt to response output.

  ## Get started
  Set up full-stack observability for your Anthropic applications using OpenLLMetry — an OpenTelemetry-based instrumentation for LLMs. Once instrumented, this quickstart provides out-of-the-box dashboards and alerts to monitor your Anthropic Claude models (Haiku, Sonnet & Opus).

summary: |
  Monitor end-to-end your Anthropic services such as Haiku, Sonnet, and Opus with real-time metrics, cost tracking, and tracing via OpenLLMetry.

icon: logo.png
level:
  - New Relic
authors:
  - New Relic
title: Anthropic
documentation:
  - name: Anthropic integration documentation
    description: |
      Set up full-stack observability for your Anthropic-powered GenAI applications using OpenLLMetry and New Relic.
    url: https://github.com/traceloop/openllmetry
dataSourceIds:
  - opentelemetry
keywords:
  - anthropic
  - anthropic ai
  - claude
  - haiku
  - sonnet
  - opus
  - llm
  - large language model
  - generative ai
  - ai
  - artificial intelligence
  - mlops
  - opentelemetry
  - openllmetry
  - NR1_addData
alertPolicies:
  - anthropic
dashboards:
  - anthropic
