id: salesforce-eventlog-for-logs
displayName: Salesforce Exporter integration for New Relic
description: |
  Monitor Salesforce platform performance, usage and security, using events generated in Salesforce
install:
  primary:
    link:
      url: https://github.com/newrelic/newrelic-salesforce-exporter/
icon: logo.png
