slug: compute-governance-breakdown
title: Compute Governance Breakdown
description: |
  This quickstart provides a granular, diagnostic view of your consumption, specifically designed to decode how Compute Capacity Units (CCUs) are distributed across your environment. It transforms raw billing data into actionable intelligence by mapping spend directly to specific user behaviors and technical configurations.
summary: |
  An intuitive, customizable dashboard for deep analysis of the sources of CCU usage.

# Support level: New Relic | Verified | Community (required)
level: Community

# Authors of the quickstart (required)
authors:
  - Dylan Meyer

# Keywords for filtering / searching criteria in the UI
keywords:
  - New Relic Compute
  - Consumption Analysis
  - CCU Usage

# Reference to dashboards to be included in this quickstart
dashboards:
  - compute-governance-breakdown

# Documentation references
documentation:
  - name: Pricing & Billing
    url: https://docs.newrelic.com/docs/accounts/accounts-billing/new-relic-one-pricing-billing/new-relic-one-pricing-billing/
    description: Understand how each pricing model works and which capabilities require Core vs. Advanced Compute.
  - name: Compute Optimizer
    url: https://docs.newrelic.com/docs/accounts/accounts-billing/new-relic-one-pricing-billing/compute-optimizer/
    description: A step-by-step guide to using the Compute Optimizer.
  - name: Consumption Management
    url: https://docs.newrelic.com/docs/accounts/accounts-billing/new-relic-one-pricing-billing/consumption-management/
    description: Learn how to analyze and understand your Compute consumption. 
  - name: Compute Budgets
    url: https://docs.newrelic.com/docs/accounts/accounts-billing/new-relic-one-pricing-billing/compute-budgets/overview/
    description: Proactively monitor your costs to improve budget confidence and adherence.
  - name: Usage Queries & Alerts
    url: https://docs.newrelic.com/docs/accounts/accounts-billing/new-relic-one-pricing-billing/usage-queries-alerts/
    description: Create custom NRQL queries to gain granular visibility into your consumption and set up specific alerts.

# Content / Design
icon: logo.svg
