id: browser-web-sockets
displayName: Browser Websockets
description: |
  Utilize Browser WebSocket events to analyze telemetry and performance data of your websockets connections.
install:
  primary:
    link:
      url: https://docs.newrelic.com/docs/browser/new-relic-browser/browser-pro-features/websockets/
icon: logo.svg
