id: browser-web-sockets
displayName: Browser Web Sockets
description: |
  Utilize Browser WebSocket events to analyze telemetry and performance data of your web sockets connections.
install:
  primary:
    link:
      url: https://docs.newrelic.com/attribute-dictionary/?dataSource=Browser+agent&event=WebSocket
icon: logo.svg
