id: redis-otel
displayName: Redis (OpenTelemetry)
description: |
  The OpenTelemetry Redis receiver enables the collection of metrics related to clients, connections, memory usage, network, and more.
install:
  primary:
    nerdlet:
      nerdletId: marketplace.install-data-source
      nerdletState:
        dataSourceId: redis-otel
        frameworkConfigId: redis-otel
      requiresAccount: false

icon: logo.svg

keywords:
  - infrastructure
  - database
  - db
  - open source
  - open telemetry
  - redis otel
  - opentelemetry redis

categoryTerms:
  - infrastructure
  - open source monitoring
