id: 2cc13c93-462e-4d7b-8c2c-be822d58c3a7
slug: browser-web-sockets
title: Browser Websockets
summary: Example dashboards utilizing websockets from New Relic Browser agent data
description: |
  Utilize Browser WebSocket events to analyze telemetry and performance data of your websockets connections.
level: New Relic
authors:
  - Grady Ellison
icon: logo.svg
documentation:
  - name: Browser Websockets
    description: Browser WebSocket events are captured when a WebSocket connection lifecycle completes — either when the connection closes normally or when the page navigates away with an open connection. It includes metrics about the connection, messages received, data sent, and how the connection was closed. Each WebSocket instance is tracked independently and emits one event per connection lifetime.
    url: https://docs.newrelic.com/docs/browser/new-relic-browser/browser-pro-features/websockets/
dataSourceIds:
  - browser-web-sockets
keywords:
  - browser agent
  - web
  - javascript
  - chrome
  - firefox
  - safari
  - performance
  - socket
  - timing
  - duration
dashboards:
  - browser-web-sockets
